### ISSUE TITLE
Npm upload is not working

### ISSUE THREAD

**Issue by g4s8** [artipie/npm-adapter#41]
`npm` CLI tool failed to upload a package to NPM repository. It's working for `file` storage and was working for NPM too previously.
Steps to reproduce:
 - create repository config. put it to relative `./repo` directory with `npm.yaml` name:
```yaml
repo:
  type: npm
  storage:
    type: fs
    path: /var/artipie/npm-storage
```
 - start Artipie Docker using
```bash
docker run -v $PWD:/var/artipie -p 80:80 artipie/artipie:0.1.2
```
 - try to upload npm package by using `npm  --registry=http://localhost/npm/ publish`

It fails with 500 error without error message.
